version: '3.7'
services:
  rabbit:
    image: cloudio/cloudio-rabbitmq:latest
    ports:
    - "8883:8883"
    - "5671:5671"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CA_CERT: ${CA_CERT}
      SERVER_CERT: ${SERVER_CERT}
      SERVER_KEY: ${SERVER_KEY}

  influx:
    image: influxdb:latest

  mongo:
    image: mongo:latest

  services:
      image: cloudio/cloudio-services:0.2.0-SNAPSHOT
      ports:
      - "80:8080"
      links:
      - rabbit
      - influx
      - mongo
      volumes:
      - "./certificates:/etc/cloudio"
      environment:
        spring.rabbitmq.username: 'admin'
        spring.rabbitmq.password: ${ADMIN_PASSWORD}
        spring.rabbitmq.host: 'rabbit' 
        spring.rabbitmq.ssl.key-store: 'file:/etc/cloudio/cloudio_services.p12'
        spring.rabbitmq.ssl.trust-store: 'file:/etc/cloudio/ca.jks'
        spring.rabbitmq.ssl.trust-store-password: 'cloudioDEV'
        cloudio.cert-manager.caCertificate: ${CA_CERT}
        cloudio.cert-manager.caPrivateKey: ${CA_KEY}
        spring.data.mongodb.host: 'mongo'
        spring.data.mongodb.database: 'cloudio'
        spring.influx.url: 'http://influx:8086'
